In [28]:
#套件參考 https://kaiching.org/pydoing/py/python-library-ospath.html

print("1","-"*100)
import os
print(os.getcwd())

print("2","-"*100)
print(os.listdir())

print("3","-"*100)
import sys
print(sys.path)
print(sys.version)

print("4","-"*100)
import random
print(random.random())
print(random.randint(1,10))
print(random.sample("This is a book",4))

for i in range(10):
    print(random.random())
    print(random.randint(1,10))

1 ----------------------------------------------------------------------------------------------------
/Users/ChungKai/Documents/Python/Python爬蟲基礎班
2 ----------------------------------------------------------------------------------------------------
['text2', 'test4.txt', '.DS_Store', 'test1.txt', '20190516.ipynb', '練習題.ipynb', '20190509.ipynb', '.ipynb_checkpoints', '20190508.ipynb']
3 ----------------------------------------------------------------------------------------------------
['/Users/ChungKai/Documents/Python/Python爬蟲基礎班', '/anaconda3/lib/python37.zip', '/anaconda3/lib/python3.7', '/anaconda3/lib/python3.7/lib-dynload', '', '/anaconda3/lib/python3.7/site-packages', '/anaconda3/lib/python3.7/site-packages/aeosa', '/anaconda3/lib/python3.7/site-packages/IPython/extensions', '/Users/ChungKai/.ipython']
3.7.3 (default, Mar 27 2019, 16:54:48)
[Clang 4.0.1 (tags/RELEASE_401/final)]
4 ----------------------------------------------------------------------------------------------------
0.27161758057391205
4
['i', 'i', ' ', 's']
0.1213350698318223
8
0.24942590284203914
10
0.676228833662343
6
0.17014079938904203
1
0.42382763081535
9
0.9677736574806003
8
0.5735255590706372
1
0.03842155391258506
7
0.3090683990653572
9
0.6087960463494411
7

In [38]:
import os

location = os.getcwd()
print(location)
print(location.split("/"))

/Users/ChungKai/Documents/Python/Python爬蟲基礎班
['', 'Users', 'ChungKai', 'Documents', 'Python', 'Python爬蟲基礎班']

In [51]:
import pandas as pd

df3 = pd.read_csv("sample.csv")
df3

,貨品分類,中文貨名,英文貨名,國家,數量,數量單位,重量,重量單位,價值
0,3032300007,冷凍吳郭魚,"Tilapias, frozen",巴林,0,-,8000,KGM,411
1,3032300007,冷凍吳郭魚,"Tilapias, frozen",日本,0,-,10800,KGM,696
2,3032300007,冷凍吳郭魚,"Tilapias, frozen",加拿大,0,-,108631,KGM,7365
3,3032300007,冷凍吳郭魚,"Tilapias, frozen",沙烏地阿拉伯,0,-,503000,KGM,24919
4,3032300007,冷凍吳郭魚,"Tilapias, frozen",其他大洋洲國家,0,-,11695,KGM,729
5,3032300007,冷凍吳郭魚,"Tilapias, frozen",阿拉伯聯合大公國,0,-,29000,KGM,1274
6,3032300007,冷凍吳郭魚,"Tilapias, frozen",科威特,0,-,121536,KGM,6128
7,3032300007,冷凍吳郭魚,"Tilapias, frozen",美國,0,-,749982,KGM,46022
8,3032300007,冷凍吳郭魚,"Tilapias, frozen",香港,0,-,72,KGM,2
9,3032300007,冷凍吳郭魚,"Tilapias, frozen",澳大利亞,0,-,69570,KGM,4786
10,3032300007,冷凍吳郭魚,"Tilapias, frozen",關島,0,-,8618,KGM,458
11,12019000104,黑豆，不論是否破碎,"Black soybeans, whether or not broken",加拿大,0,-,0,TNE,43
12,12019000104,黑豆，不論是否破碎,"Black soybeans, whether or not broken",美國,0,-,0,TNE,9
13,12019000104,黑豆，不論是否破碎,"Black soybeans, whether or not broken",菲律賓,0,-,0,TNE,6
14,52114200005,牛仔布,Denim,中國大陸,11398,MTK,1991,KGM,902
15,52114200005,牛仔布,Denim,日本,14364,MTK,3898,KGM,1596
16,52114200005,牛仔布,Denim,印尼,21998,MTK,3869,KGM,1543
17,52114200005,牛仔布,Denim,印度,7212,MTK,2185,KGM,513
18,52114200005,牛仔布,Denim,柬埔寨,28081,MTK,9915,KGM,2469
19,52114200005,牛仔布,Denim,馬來西亞,8925,MTK,3598,KGM,575
20,52114200005,牛仔布,Denim,越南,139191,MTK,53225,KGM,12330
21,52114200005,牛仔布,Denim,賴索托,6894,MTK,2771,KGM,435

In [52]:
import pandas as pd
df3 = pd.read_csv("sample.csv")
df3["中文貨名"]

0         冷凍吳郭魚
1         冷凍吳郭魚
2         冷凍吳郭魚
3         冷凍吳郭魚
4         冷凍吳郭魚
5         冷凍吳郭魚
6         冷凍吳郭魚
7         冷凍吳郭魚
8         冷凍吳郭魚
9         冷凍吳郭魚
10        冷凍吳郭魚
11    黑豆，不論是否破碎
12    黑豆，不論是否破碎
13    黑豆，不論是否破碎
14          牛仔布
15          牛仔布
16          牛仔布
17          牛仔布
18          牛仔布
19          牛仔布
20          牛仔布
21          牛仔布
Name: 中文貨名, dtype: object

In [68]:
import pandas as pd
df3 = pd.read_csv("sample.csv")

df3["重量(噸)"] = df3["重量"] / 1000
df3["價值(台幣)"] = df3["價值"] *30
df3["簡稱1"]=df3["中文貨名"][0:2]
df3["簡稱2"]=df3["中文貨名"].str[0:2]

#統一取代欄位資料
df3["數量單位"]="-!"

#過濾資料
df3["中文貨名"]=="冷凍吳郭魚"
df3[df3["中文貨名"]=="冷凍吳郭魚"]

,貨品分類,中文貨名,英文貨名,國家,數量,數量單位,重量,重量單位,價值,重量(噸),價值(台幣),簡稱1,簡稱2
0,3032300007,冷凍吳郭魚,"Tilapias, frozen",巴林,0,-!,8000,KGM,411,8.000,12330,冷凍吳郭魚,冷凍
1,3032300007,冷凍吳郭魚,"Tilapias, frozen",日本,0,-!,10800,KGM,696,10.800,20880,冷凍吳郭魚,冷凍
2,3032300007,冷凍吳郭魚,"Tilapias, frozen",加拿大,0,-!,108631,KGM,7365,108.631,220950,NaN,冷凍
3,3032300007,冷凍吳郭魚,"Tilapias, frozen",沙烏地阿拉伯,0,-!,503000,KGM,24919,503.000,747570,NaN,冷凍
4,3032300007,冷凍吳郭魚,"Tilapias, frozen",其他大洋洲國家,0,-!,11695,KGM,729,11.695,21870,NaN,冷凍
5,3032300007,冷凍吳郭魚,"Tilapias, frozen",阿拉伯聯合大公國,0,-!,29000,KGM,1274,29.000,38220,NaN,冷凍
6,3032300007,冷凍吳郭魚,"Tilapias, frozen",科威特,0,-!,121536,KGM,6128,121.536,183840,NaN,冷凍
7,3032300007,冷凍吳郭魚,"Tilapias, frozen",美國,0,-!,749982,KGM,46022,749.982,1380660,NaN,冷凍
8,3032300007,冷凍吳郭魚,"Tilapias, frozen",香港,0,-!,72,KGM,2,0.072,60,NaN,冷凍
9,3032300007,冷凍吳郭魚,"Tilapias, frozen",澳大利亞,0,-!,69570,KGM,4786,69.570,143580,NaN,冷凍
10,3032300007,冷凍吳郭魚,"Tilapias, frozen",關島,0,-!,8618,KGM,458,8.618,13740,NaN,冷凍

In [71]:
import pandas as pd
df3 = pd.read_csv("sample.csv")

df3[ (df3["中文貨名"] =="牛仔布") & (df3["價值"] >= 400)]

           貨品分類 中文貨名    英文貨名    國家      數量  數量單位     重量  重量單位     價值
14  52114200005  牛仔布   Denim  中國大陸   11398  MTK    1991  KGM     902
15  52114200005  牛仔布   Denim    日本   14364  MTK    3898  KGM    1596
16  52114200005  牛仔布   Denim    印尼   21998  MTK    3869  KGM    1543
17  52114200005  牛仔布   Denim    印度    7212  MTK    2185  KGM     513
18  52114200005  牛仔布   Denim   柬埔寨   28081  MTK    9915  KGM    2469
19  52114200005  牛仔布   Denim  馬來西亞    8925  MTK    3598  KGM     575
20  52114200005  牛仔布   Denim    越南  139191  MTK   53225  KGM   12330
21  52114200005  牛仔布   Denim   賴索托    6894  MTK    2771  KGM     435

In [105]:
#價值總和
import pandas as pd
data = pd.read_csv("sample.csv")

data["價值"]
sum(data["價值"])


# data["價值"].sum() 也可以

113211

In [108]:
#冷凍吳郭魚價值大於一千的重量和

import pandas as pd
data = pd.read_csv("sample.csv")


data[(data["中文貨名"] == "冷凍吳郭魚") & (data["重量"] > 1000)]["重量"].sum()

1620832

In [103]:
#牛仔布與冷凍吳郭魚的貿易差
import pandas as pd
data = pd.read_csv("sample.csv")

dataA = data[data["中文貨名"] =="牛仔布"]
sumA = sum(dataA["價值"])
dataB = data[data["中文貨名"] =="冷凍吳郭魚"]
sumB = sum(dataB["價值"])
sumA - sumB

-72427

In [113]:
#牛仔布與冷凍吳郭魚的貿易差
import pandas as pd
data = pd.read_csv("sample.csv")

data[data["中文貨名"] == "冷凍吳郭魚"]["價值"].sum() - data[data["中文貨名"] == "牛仔布"]["價值"].sum()

72427

In [128]:
math = [
    {"name":"Jeff", "score":12},
    {"name":"Leo", "score":63},
    {"name":"Kevin", "score":100},
    {"name":"Apple", "score":77},
    {"name":"Elle", "score":84},
    {"name":"Emma", "score":60},
]

eng = [
    {"name":"Jeff", "score":58},
    {"name":"Leo", "score":100},
    {"name":"Kevin", "score":97},
    {"name":"Apple", "score":85},
    {"name":"Elle", "score":92},
    {"name":"Emma", "score":41},
]

def getScoresSum(data):
    result = 0
    
    for ele in data:
        result += ele["score"]
    return result

def getScoresAve(data):
    result = 0 
    for ele in data:
        result += ele["score"]
    return result / len (data)


def getFailedList(data):
    result = []
    for ele in data:
        if ele["score"] < 60:
            result.append(ele["name"])
    return

mathSum= getScoresSum(math)
engAve = getScoresAve(eng)
mathFailed = getFailedList(math)

print(mathSum)
print(engAve)
print(mathFailed)

396
78.83333333333333
None

In [141]:
#類別

class Person:
    def __init__(self,name,age):
        self.name = name
        self.age = age
    def sayMyName(self):
        print("HiHi, I am {}".format(self.name))
    def showMyAge(self):
        print("I am {} years old.".format(self.age))
        
person1 = Person("Jeff",18)
person2 = Person("Leo",22)


person1.sayMyName()
person1.showMyAge()

HiHi, I am Jeff
I am 18 years old.

In [159]:
class Shoe:
    city = "Taipei"
    
    #先定義class的動態物件內容，__init__是用來定義物件，第一個參數是物件（必為self)，接下來就是屬性（如size,price）
    def __init__(self,size,price):
        self.size = size
        self.price = price
    
    def showMySize(self):
            print("My size is",format(self.size))
    
    def showThePrice(self):
            print("This Shoe costs",format(self.price))

shoe1 = Shoe(9,1000)
shoe2 = Shoe(12,2500)

shoe1.showMySize()
shoe2.showThePrice()

My size is 9
This Shoe costs 2500

In [160]:
### By Class
class EngClass:
    def __init__(self,data):
        self.data = data
        
    def getScoresAvg(self):
        result = 0
        for ele in self.data:
            result += ele["score"]
        return result / len(self.data)
    
    
class MathClass:
    def __init__(self,data):
        self.data = data
        
    def getScoresAvg(self):
        result = 0
        for ele in self.data:
            result += ele["score"]
        return result / len(self.data)
        

mathStudScores = [
    {"name":"Jeff", "score":95},    
    {"name":"Leo" , "score":63},
    {"name":"Keven", "score":100},
    {"name":"Apple", "score":77},
    {"name":"Elle", "score":84},
    {"name":"Emma", "score":60},
]

engStudScores = [
    {"name":"Jeff","score":58},    
    {"name":"Leo", "score":100},
    {"name":"Keven","score":97},
    {"name":"Apple","score":85},
    {"name":"Elle","score":92},
    {"name":"Emma","score":41},
]

# 數學 : 總合
# 英文 : 平均 & 不及格名單

###
# Definition
### Mathsult
    
###
# Main
engClass = EngClass(engStudScores)
print("Eng Avg : ",engClass.getScoresAvg())

mathClass = MathClass(mathStudScores)
print("Math Avg : ",mathClass.getScoresAvg())

Eng Avg :  78.83333333333333
Math Avg :  79.83333333333333